theme: jekyll-theme-minimal
title: yaoz
description: 备忘，总结，展示。
timezone: Asia/Shanghai
logo: /assets/yaoz.png
show_downloads: false
lang: zh
truncate: 10
kramdown:
  hard_wrap: true
  toc_levels: [1, 2, 3, 4, 5]