theme: jekyll-theme-minimal
title: yao_z
description: 备忘，总结，展示。
timezone: Asia/Shanghai
logo: /assets/yaoz.png
show_downloads: false
lang: zh
truncate: 20
kramdown:
  hard_wrap: true
  toc_levels: [2, 3, 4, 5, 6]